### ISSUE TITLE
Shortcuts to toggle comment don't work

### ISSUE THREAD

**Issue by Boscop** [ron-rs/sublime-ron#3]
Please add support for Ctrl+/ and Ctrl+Shift+/ to toggle line/multi-line comments :)

**Comment by Boscop** [comment]
@kvark Could you please add support for these shortcuts, at least toggling line comments?
It would be very appreciated! :)
The lack of this is the biggest pain point with the RON editing experience..

**Comment by kvark** [comment]
I don't know how to do this (and not using these shortcuts myself). Some of us need to investigate and make a PR :)

**Comment by Boscop** [comment]
@kvark So which editor do you use for RON and how do you toggle comments? :)

**Comment by kvark** [comment]
I use ST4, but I just don't have a habit of toggling the comments on/off.
