### ISSUE TITLE
Highlighting is messed up as soon as I add attributes

### ISSUE THREAD

**Issue by Boscop** [ron-rs/sublime-ron#6]
The syntax highlighting in Sublime is messed up as soon as I add attributes:

![image](https://user-images.githubusercontent.com/535593/86289081-566e4f80-bbeb-11ea-80df-4c5939a1ceee.png)

**Comment by entropylost** [comment]
Is there any progress on this?

**Comment by torkleyy** [comment]
Please check if #7 fixes it @iMplode-nZ
